# Default values for godaddy-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/snowdrop/cert-manager-webhook-godaddy
  tag: latest
  pullPolicy: IfNotPresent

pod:
  securePort:

groupName: acme.mycompany.com

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# The secret token in the form "GODADDY_API_KEY:GODADDY_API_SECRET"
token: ""

clusterIssuer:
  enabled: false
  # Acme endpoint.
  # Defaults to letsencrypt stage.
  # Use https://acme-v02.api.letsencrypt.org/directory for prod.
  name: letsencrypt-staging
  endpoint: https://acme-staging-v02.api.letsencrypt.org/directory
  email: foo@cluster.local
  # 
  selector:
    dnsZones:
    - 'example.com'

